# This is a basic workflow to help you get started with Actions

name: Remind Pull Request

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    container: rubylang/ruby

    steps:
      - uses: actions/checkout@v2

      - name: Bundle install
        run: bundle install -j4

      - name: Run a raketask
        run: rake remind_pull_request
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          PR_LABEL: ${{ secrets.PR_LABEL }}
